### ISSUE TITLE
XDG_DATA_DIR reset to default

### ISSUE THREAD

**Issue by jhgoebbert** [Xpra-org/xpra#3505]
--- introduction ---
We are setting the the following environment variables before we start xpra.
- XDG_MENU_PREFIX=jsc-
- XDG_CONFIG_DIRS=<mypath>/config:...
- XDG_DATA_DIRS=<mypath>/data:...

That allows us to set the application-menu specific to the situation. It was working in the past with xpra 4.0.4.
But with xpra 4.3.2 this is now not working anymore because XDG_DATA_DIRS were reset to the system default.

--- tracking the bug ---
I figured that the reason for this redefinition of XDG_DATA_DIRS comes from the line
```
os.environ.update(source_env(opts.source))
```
in server.py:940
https://github.com/Xpra-org/xpra/blob/v4.3.2/xpra/scripts/server.py#L940

Before that line XDG_DATA_DIRS is defined as desired to a list of directories including `<mypath>/data`
But after that line it is cleaned and set to `/usr/local/share:/usr/share` only.

The reason seems to me that `opts.source` is set to `/etc/profile` and 
```
source_env('/etc/profile') 
```
from https://github.com/Xpra-org/xpra/blob/v4.3.2/xpra/server/server_util.py#L25
calls
```
e = env_from_sourcing(['/etc/profile'])
```
which overwrites environment settings by loading `/etc/profile` and passing them to `os.environ.update`

--- expected behaviour ---
The expected behaviour for me would be that xpra respects the current XDG_* environment variables without overwriting them by reloading the environment from `/etc/profile`. This leads to failure when setting up the Xpra-menu as data entries cannot be found.

**Comment by totaam** [comment]
This is working as intended, see #2688 for details.

You can:
* remove `source = /etc/profile` from `/etc/xpra/conf.d/60_server.conf`
And with git master:
* use the `env` command line option, ie: `--env=XDG_DATA_DIRS=whatever` etc.
* add `--source=no`

**Comment by jhgoebbert** [comment]
Thank you for your hints! 

As I cannot configure xpra through `/etc/xpra` or `$HOME/.local` I would like to ask you to accept my PR ( https://github.com/Xpra-org/xpra/pull/3507 ) to read/use XPRA_SYSCONF_DIR also on a posix system.
