### ISSUE TITLE
clipboard not working: object has no attribute get_xid

### ISSUE THREAD

**Issue by blob42** [Xpra-org/xpra#3867]
**Describe the bug**
The clipboard stopped working for me. I don't know since when it broke. 

**EDIT:**
It works on version: v4.4.5-r0 (both server-client)

**To Reproduce**
- Select and copy text on client window.
- Paste on client machine.
- 
**System Information (please complete the following information):**
 - Server OS: Arch Linux
 - Client OS: Arch Linux
 - Xpra Server Version: tried 68995db and HEAD
 - Xpra Client Version: tried 68995db and HEAD

gtk3 1:3.24.37-1
glib2 2.76.1-1
glibc 2.37-2
xorg-server 21.1.8-1

**Additional context**
```

AttributeError: 'int' object has no attribute 'get_xid'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/xpra/client/base/client_base.py", line 1198, in call_handler
    handler(packet)
  File "/usr/lib/python3.11/site-packages/xpra/client/mixins/clipboard.py", line 243, in _process_clipboard_packet
    ch.process_clipboard_packet(packet)
  File "/usr/lib/python3.11/site-packages/xpra/clipboard/clipboard_core.py", line 509, in process_clipboard_packet
    handler(packet)
  File "/usr/lib/python3.11/site-packages/xpra/clipboard/clipboard_core.py", line 478, in _process_clipboard_contents
    self._clipboard_got_contents(request_id, dtype, dformat, raw_data)
  File "/usr/lib/python3.11/site-packages/xpra/clipboard/clipboard_timeout_helper.py", line 122, in _clipboard_got_contents
    proxy.got_contents(target, dtype, dformat, data)
  File "/usr/lib/python3.11/site-packages/xpra/x11/gtk_x11/clipboard.py", line 510, in got_contents
    self.set_selection_response(requestor, actual_target, prop, dtype, dformat, data, time)
  File "/usr/lib/python3.11/site-packages/xpra/x11/gtk_x11/clipboard.py", line 474, in set_selection_response
    xid = requestor.get_xid()
          ^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'get_xid'
```

**Comment by totaam** [comment]
@blob42 please try the commit above.

**Comment by blob42** [comment]
@totaam Thanks for the quick fix. 

I updated first on the client side and it worked fine. 
However on the server I cannot use HEAD I get this error when I start xpra server:
```
    from xpra.x11.gtk_x11.tray import get_tray_window, SystemTray
  File "/usr/lib/python3.11/site-packages/xpra/x11/gtk_x11/tray.py", line 94, in <module>
    class SystemTray(GObject.GObject):
  File "/usr/lib/python3.11/site-packages/xpra/x11/gtk_x11/tray.py", line 183, in SystemTray
    def get_pywindow(self, xid:int) -> GdkX11.Window:
                                       ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.GdkX11' object has no attribute 'Window'
```

I have `extra/gtk3 1:3.24.38-1 [installed]`

**Comment by totaam** [comment]
@blob42 sorry about that, not sure why I didn't catch it before pushing, e376ce88a680e7b64243f9e69a4d6c9ae1e7acd6 fixes that.

**Comment by blob42** [comment]
@totaam no worries thanks for the fix no more errors now.
