### ISSUE TITLE
xpra 5.0-r0-1 problems on Ubuntu 20.04.6 - ImportError: cannot import name 'TypeAlias' from 'typing_extensions'

### ISSUE THREAD

**Issue by nentibusarchitectura** [Xpra-org/xpra#3980]
**Describe the bug**

After upgrading xpra to v5.0

xpra breaks with the message:

```
user@workstation:~$ xpra
Traceback (most recent call last):
  File "/usr/bin/xpra", line 16, in <module>
    from xpra.scripts.main import main
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 38, in <module>
    from xpra.scripts.parsing import (
  File "/usr/lib/python3/dist-packages/xpra/scripts/parsing.py", line 20, in <module>
    from xpra.net.common import DEFAULT_PORT, DEFAULT_PORTS
  File "/usr/lib/python3/dist-packages/xpra/net/common.py", line 9, in <module>
    from typing_extensions import TypeAlias
ImportError: cannot import name 'TypeAlias' from 'typing_extensions' (/usr/lib/python3/dist-packages/typing_extensions.py)
```

**To Reproduce**
Install xpra with ```apt dist-upgrade```

**System Information (please complete the following information):**
 - Server OS: Ubuntu 20.04.6
 - Client OS: Ubuntu 20.04.6
 - Xpra Server Version: 4.4.6-r29-1
 - Xpra Client Version: xpra 5.0-r0-1

**Additional context**

I've managed to solve the issue with:

```pip3 install typing-extensions --upgrade```

**Comment by totaam** [comment]
Already fixed and will be included in 5.0.1:
https://github.com/Xpra-org/xpra/commit/a392929946697f104c060ea4152edb5981bf32e5

**Comment by nentibusarchitectura** [comment]
Thank you so much.

In the end I had to go back to 4.4.6 due to other issues.

There are a number of other issues I've noticed (teething I guess :-) ), once I get some time I will fill separate reports for them, on the positive 5.0.x feels faster and snappier.

If anybody is interested in reverting to 4.4.6:

``dpkg --remove xpra xpra-x11
apt install xpra=4.4.6-r29-1
apt-hold xpra # If you want to prevent upgrades to 5.x``
