### ISSUE TITLE
Distorted text when scrolling

### ISSUE THREAD

**Issue by c0xc** [Xpra-org/xpra#4586]
**Describe the bug**
In seamless mode, screen portions are distorted when scrolling, making text unreadable. See attached screen recording.

https://github.com/user-attachments/assets/a3200175-6920-4cca-9d9b-cafa2b47d603

Server version xpra v6.4-r37819 (beta), client v6.3-r0, both Fedora 40.

**To Reproduce**
1. server command: e.g., xpra start :5 --start=mate-terminal
2. client command: xpra attach ssh://.../5
3. specific action to trigger the bug: use the wheel to scroll in the browser

**System Information (please complete the following information):**
 - Server OS: Fedora 40
 - Client OS: Fedora 40
 - Xpra Server Version v6.4
 - Xpra Client Version v6.3

**Additional context**
I used to have similar glitches on another server (same version now) which could be mostly resolved by selecting H.264 as encoding.
Changing the picture quality / speed settings does not seem to help.

I've found similar issues like #4046 but from reading them, it's not clear to me if they describe the same problem.

Sometimes a new browser tab would be all blank until you begin to scroll or highlight something. 

According to the session info dialog, the H264 encoding is available both on the client and on the server (although it's not just one single system that's affected).

What am I missing?

**Comment by totaam** [comment]
Can you reproduce with the python client?
This looks like #4440 
If so, disabling scroll encoding or offscreen decoding should help.

**Comment by c0xc** [comment]
I can always reproduce it in seamless mode, so I would start something like `xpra start :5 --start=mate-terminal` and launch a browser from there (Firefox seems worse, not sure). It was exteme but it would stop when I select h264, that's not true anymore. I've just tried two Fedora servers, both with xpra v6.4-r37819 and client xpra v6.3-r0 (but it also happens between the two systems running 6.4).

I've now started the server like this:

    xpra start :11 --start=chromium-browser -d compress

And attached:

    xpra attach ssh://.../11 -d video

I've made a new screenrecording, does this help?

https://github.com/user-attachments/assets/13fd860e-773e-4ed6-bc34-a03eb522f5f3

Server log:
...
compress: 103.8ms for 1438x1296 pixels at    0,51   for wid=1     using      webp with ratio   4.3%  ( 7280KB to   316KB), sequence   334, client_options={'rgb_format': 'BGRX', 'quality': 100, 'encoder': 'webp', 'flush': 0}, options=typedict({'optimize': False, 'auto_refresh': True, 'quality': 100, 'speed': 50, 'rgb_formats': ('YUV420P', 'YUV422P', 'YUV444P', 'NV12', 'GBRP', 'BGRA', 'BGRX', 'RGBA', 'RGBX', 'RGB', 'BGR'), 'lz4': True, 'content-type': 'browser', 'window-size': (1444, 1347), 'damage-time': 12344700.3069111, 'process-damage-time': 12344700.312557215, 'depth': 24})
```

When selecting h264 on the client, these appear:
```
client   4 @32.990 get_video_decoding_options() will try video decoders: {'dec_openh264': <module 'xpra.codecs.openh264.decoder' from '/usr/lib64/python3.12/site-packages/xpra/codecs/openh264/decoder.cpython-312-x86_64-linux-gnu.so'>, 'dec_vpx': <module 'xpra.codecs.vpx.decoder' from '/usr/lib64/python3.12/site-packages/xpra/codecs/vpx/decoder.cpython-312-x86_64-linux-gnu.so'>}
2025-05-26 13:50:08,181 client   4 @32.991 get_video_decoding_options()={'h264': {'YUV420P': [openh264(YUV420P to h264)]}, 'vp8': {'YUV420P': [vpx(YUV420P to vp8)]}, 'vp9': {'YUV420P': [vpx(YUV420P to vp9)], 'YUV444P': [vpx(YUV444P to vp9)]}}
2025-05-26 13:50:08,181 Error: unknown or invalid packet type 'encoding'
2025-05-26 13:50:08,181  received from Protocol(socket socket:@xpra/11)
```

**Comment by totaam** [comment]
Sorry, but I can't parse text from a video recording.
I will have to try to find the time to reproduce it.
In the meantime, you may want to play with `--opengl=no` / `--opengl=force` to see if it makes any difference.

**Comment by c0xc** [comment]
I am attaching the server log (with `-d compress`) and the client log (with `-d video`).

[xpra_attach.log](https://github.com/user-attachments/files/20444941/xpra_attach.log)
[xpra_server_compress.log](https://github.com/user-attachments/files/20444942/xpra_server_compress.log)

I attached without specifying an encoding, reproduced some of this rectangular flickering (for the lack of a better term) and then I manually selected h264 (which triggers the error at line 592).

When it happens, it seems like the client log usually indicates vp8/YUV420P unless I attach with h264:

```
2025-05-26 20:39:58,776 choose_decoder([vpx(YUV420P to vp8)])=vpx(YUV420P to vp8)
2025-05-26 20:39:58,776 paint_with_video_decoder: new vpx('vp8', 1384, 146, 'YUV420P')
2025-05-26 20:39:58,777 paint_with_video_decoder: info={'type': 'vpx', 'width': 1384, 'height': 146, 'encoding': 'vp8', 'frames': 0, 'colorspace': 'YUV420P', 'max_threads': 7}
2025-05-26 20:39:58,832 choose_decoder([vpx(YUV420P to vp8)])=vpx(YUV420P to vp8)
2025-05-26 20:39:58,832 paint_with_video_decoder: new vpx('vp8', 1384, 145, 'YUV420P')
2025-05-26 20:39:58,832 paint_with_video_decoder: info={'type': 'vpx', 'width': 1384, 'height': 145, 'encoding': 'vp8', 'frames': 0, 'colorspace': 'YUV420P', 'max_threads': 7}
2025-05-26 20:39:59,740 paint_with_video_decoder: video dimensions have changed from (1384, 145) to (1384, 95)
2025-05-26 20:39:59,741 choose_decoder([vpx(YUV420P to vp8)])=vpx(YUV420P to vp8)
2025-05-26 20:39:59,741 paint_with_video_decoder: new vpx('vp8', 1384, 95, 'YUV420P')
2025-05-26 20:39:59,741 paint_with_video_decoder: info={'type': 'vpx', 'width': 1384, 'height': 95, 'encoding': 'vp8', 'frames': 0, 'colorspace': 'YUV420P', 'max_threads': 6}
```

Attaching with or without opengl does not help. I've also tried a couple of encoding + quality=100 + speed combinations. After some changes, I thought it had stopped but then it came back, so I'm not seeing a pattern yet.

If there's anything I should check or debug, do let me know. I appreciate your help.

**Comment by totaam** [comment]
> Seems some of my settings didn't take effect?
> (..)
> meaning the menu selection has no effect at all

That's an issue with some of the beta builds, running against older builds.
I believe this was fixed.

> Xpra Server Version v6.4

That's nowhere near precise enough.

> I do see quality dropping below 100% at least one percentage point.

That's perceptually lossless. (ie: jpeg)

**Comment by totaam** [comment]
Found lots of different related issues:
* clearly something is wrong with scroll encoding (with and without opengl enabled makes no difference) so it is disabled again now: 47de5be731bcddda60015c10eabecea8dcb5093a and moved to #4596
* d5e6f9936ed8c1fb358b51a15087f9ed281408ab - no biggie but more correct
* 43d5454955df375208bffaed317df40791fbeb06 should help clients that decode and paint the `openh264` encoder's stream without accessing the side channel metadata, ie: html5 client
* downscaling during colorspace conversion could drop the `full-range` metadata flag: 01d686d93cc09117d6b2e5139c06b555b37e1dde
* the `openh264` codecs failed to preserve the `full-range` metadata
* similar problem with `vp9` with `YUV444P` input: b17f060739f3a629b87b46e08e9511d62c4688e4

I think that the reason I didn't notice this before is because I was mostly testing with nvenc, but now that my nvidia card is defunct, I am testing with `openh264` / `x264` a lot more.

@c0xc can you please try the latest beta builds and confirm that all these issues are fixed?
xpra `6.4-r38238` or later have all of these fixes.
These fixes will also be included in the 6.3.1 release.

**Comment by c0xc** [comment]
Sounds great!
So after updating _both_ server and client to v6.4-r38239 and upgrading the session, I do not see those glitches anymore when I connect normally (i.e., without specifying encoding etc.).

Text now remains readable when scrolling without having to attach with `--encodings=no-scroll`.
The extreme flickering/flashing of rectangular sections seems also gone, I'm not seeing it anymore! So I guess it was that full_range flag then (and not the compression)... I think it's fixed now!

However, I have observed some errors which may or may not be related, but they seem new to me.

`query_pulseaudio_properties` referenced in something that's not inherited from PulseaudioServer.
```
2025-06-01 19:31:36,509 OpenGL is supported on display ':11'
2025-06-01 19:31:36,510  using 'llvmpipe (LLVM 19.1.7, 256 bits)' renderer
2025-06-01 19:31:37,142 GStreamer version 1.24.11
Exception in thread audio-setup:
Traceback (most recent call last):
  File "/usr/lib64/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/usr/lib64/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/site-packages/xpra/server/subsystem/audio.py", line 114, in init_audio_options
    GLib.idle_add(self.query_pulseaudio_properties)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SeamlessServer' object has no attribute 'query_pulseaudio_properties'
2025-06-01 19:31:37,541 some GStreamer elements are missing or unavailable on this system:
2025-06-01 19:31:37,541  vah264lpenc, vah264enc, vaapih264enc, vaapih265enc
```

Plus that one, though I only saw it once and it may not be serious:
[xpra_error3.log](https://github.com/user-attachments/files/20542732/xpra_error3.log)

> ... I was mostly testing with nvenc, but now that my nvidia card is defunct, I am testing with openh264 / x264 a lot more.

Since you're mentioning it - I'm looking for compatible cards to hopefully improve bad performance (apparently related to graphics as cpu usage of xpra server often around 20% while FF, TB or whatever program is using even more, so there's at least a half a second delay when scrolling or hovering menu items in desktop mode). The FAQ mentions the Quadro 4000 model and links to Nvidia but I'm wondering if there's more to it than picking any GPU with h264 nvenc support, I was thinking of something like a "tested devices table". Either way, I don't want to get too off-topic here so feel free to ignore that comment.

Thanks again for taking the time to find and fix this!

**Comment by totaam** [comment]
> However, I have observed some errors which may or may not be related, but they seem new to me.

That's unrelated, fixed in 347faba3330155c11bdb2fb32481a0aed9da338c

> Plus that one, though I only saw it once and it may not be serious:
> (..)
> `expected YUV420P but got BGRX`

Yes, this can happen when the video pipeline is being updated asynchronously.
Nothing to worry about, the engine will fallback to a non-video frame and retry video for the next frame which almost always goes through without errors.

> The FAQ mentions the Quadro 4000

Any nvidia card should work well, though I have lost the ability to test things now that my card broke.
