### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'after_handshake'

### ISSUE THREAD

**Issue by ShadowJonathan** [Xpra-org/xpra#4006]
Originally on homebrew release (5.0.2), replicated this with a fresh clone and build (`pip install -e .`)

```
(xpra) ➜  ~/dev/xpra git:(v5.x) ✗ xpra          
grep: /usr/share/locale/locale.alias: No such file or directory
xpra main error:
Traceback (most recent call last):
  File "/Users/j0j0/dev/xpra/xpra/scripts/main.py", line 121, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/j0j0/dev/xpra/xpra/scripts/main.py", line 455, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/j0j0/dev/xpra/xpra/scripts/main.py", line 587, in do_run_mode
    return gui.main(cmdline)
           ^^^^^^^^^^^^^^^^^
  File "/Users/j0j0/dev/xpra/xpra/gtk_common/gui.py", line 258, in main
    init()
  File "/Users/j0j0/dev/xpra/xpra/platform/gui.py", line 25, in init
    do_init()
  File "/Users/j0j0/dev/xpra/xpra/platform/darwin/gui.py", line 91, in do_init
    mh = getOSXMenuHelper(None)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/j0j0/dev/xpra/xpra/platform/darwin/osx_menu.py", line 53, in getOSXMenuHelper
    _OSXMenuHelper = OSXMenuHelper(client)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/j0j0/dev/xpra/xpra/platform/darwin/osx_menu.py", line 68, in __init__
    super().__init__(client)
  File "/Users/j0j0/dev/xpra/xpra/client/gtk3/menu_helper.py", line 347, in __init__
    self.client.after_handshake(shortcut)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'after_handshake'

```

Traceback should make it obvious that the client was never instantiated.

#### System Information (please complete the following information):
 - Client OS: MacOS 13.4.1 (c) (22F770820d)
 - Xpra Client Version: v5.0.2 (c1618738fd6fe4ec24c86c08e63e6e75743a1571)

**Comment by ShadowJonathan** [comment]
This does not appear on the v5.0 and v5.0.1 tags, only on v5.0.2

**Comment by ShadowJonathan** [comment]
This got introduced by https://github.com/Xpra-org/xpra/commit/b76cca2278b98c3bbe9d764f081afc5e1a6aa884

**Comment by totaam** [comment]
> Originally on homebrew release (5.0.2), replicated this with a fresh clone and build (pip install -e .)

FYI: this is not a supported platform.

> How did this make it into a release? Why did nobody test this?

That's a very simple question to answer: I do not have the hardware required.
Would like to donate some?

The fixes are for both branches are in the commits above.

**Comment by ShadowJonathan** [comment]
> FYI: this is not a supported platform.

It's essentially just base MacOS, HomeBrew just repackages it to make it easier to install, but it is essentially the .pkg file automatically installed.

**Comment by totaam** [comment]
I have yanked the 5.0.2-r0 builds and uploaded 5.0.2-r3 with this fix.
