### ISSUE TITLE
cython build error `PyMemoryView_CheckExact` on MS Windows

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#4111]
Was wrongly attributed to clang in 11cca3625c7ade1f7cacbcf8c04ca73746f88db3.

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.ming
w_x86_64-cpython-311/xpra/buffers/cyxor.o: in function `__pyx_pf_4xpra_7buffers_5cyxor_xor_str':
E:\xpra/xpra/buffers/cyxor.c:3263:(.text+0x2aef): undefined reference to `PyMemoryView_CheckExact'
collect2.exe: error: ld returned 1 exit status
error: command 'C:\\msys64\\mingw64\\bin/gcc.exe' failed with exit code 1
```
Caused by this function signature:
https://github.com/Xpra-org/xpra/blob/7ee6be32bf1f56fb3d5a1a86b75c6d318cb5ef72/xpra/buffers/cyxor.pyx#L19

**Comment by totaam** [comment]
Caused by #4110, was added in c6230553bc4c7e33e5c6356ac609a8840b70277f.

No idea why this only fails on MS Windows!
This should be reported upstream.

**Comment by totaam** [comment]
Also seen on Linux now.

**Comment by totaam** [comment]
Also seen on Linux Fedora 40.

**Comment by totaam** [comment]
The Cython bug has been fixed so the `memoryview` type hints have been re-added: 647f8a513ed393eb75c1fd037e748f5b81d6021f
