### ISSUE TITLE
xpra version 4.3-r29154 (14b6b16b3) init problems on win10

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3139]
```
2021-05-26 10:45:04,807 Xpra GTK3 client version 4.3-r29154 (g14b6b16b3) 64-bit
2021-05-26 10:45:04,840  running on Microsoft Windows 10
2021-05-26 10:45:05,080 Error: failed to load overlay icon 'C:\Users\u\Documents\xpra-clients\Xpra-Python3-x86_64_4.3-r29154\share\xpra\icons\xpra.png':
Traceback (most recent call last):
  File "E:\xpra/xpra/client/mixins/window_manager.py", line 225, in init
  File "C:/msys64/mingw64/lib/python3.8/site-packages/PIL/Image.py", line 2967, in open
PIL.UnidentifiedImageError: cannot identify image file 'C:\\Users\\u\\Documents\\xpra-clients\\Xpra-Python3-x86_64_4.3-r29154\\share\\xpra\\icons\\xpra.png'
2021-05-26 10:45:05,085  cannot identify image file 'C:\\Users\\u\\Documents\\xpra-clients\\Xpra-Python3-x86_64_4.3-r29154\\share\\xpra\\icons\\xpra.png'
2021-05-26 10:45:10,626 GStreamer version 1.18.4 for Python 3.8.9 64-bit
2021-05-26 10:45:11,168 created named pipe 'Xpra\13852'
2021-05-26 10:45:11,524 keyboard layout code 0x409
2021-05-26 10:45:11,577 identified as 'United States - English' : us
Traceback (most recent call last):
  File "E:\xpra/xpra/client/mixins/network_listener.py", line 107, in add_listen_socket
TypeError: add_listen_socket() takes from 4 to 5 positional arguments but 6 were given
2021-05-26 10:45:12,525  keyboard settings: layout=us
2021-05-26 10:45:12,683  desktop size is 4160x1440 with 1 screen:
2021-05-26 10:45:12,742   Default (1100x381 mm - DPI: 96x96) workarea: 4160x1400
2021-05-26 10:45:12,743     Generic PnP Monitor 1600x900 at 0x534 (309x174 mm - DPI: 132x131) workarea: 1600x860 at 0x534
2021-05-26 10:45:12,750     C32JG5x 2560x1440 at 1600x0 (697x392 mm - DPI: 93x93) workarea: 2560x1400 at 1600x0
2021-05-26 10:45:12,765 Warning: cannot query ICC profiles:
2021-05-26 10:45:12,788  cannot import name 'ImageWin' from 'PIL' (C:\Users\u\Documents\xpra-clients\Xpra-Python3-x86_64_4.3-r29154\lib\PIL\__init__.pyc)
2021-05-26 10:45:18,337 enabled remote logging
2021-05-26 10:45:18,345 Xpra X11 seamless server version 4.2-r29129 64-bit
2021-05-26 10:45:18,348  running on Linux Ubuntu 20.04 focal
```

**Comment by totaam** [comment]
> `PIL.UnidentifiedImageError: cannot identify image file 'C:\\Users\\u\\Documents\\xpra-clients\\Xpra-Python3-x86_64_4.3-r29154\\share\\xpra\\icons\\xpra.png'`

That's definitely caused by #3133

> `TypeError: add_listen_socket() takes from 4 to 5 positional arguments but 6 were given`

Already fixed in a41a8a429fcea8e78c5f279f525666f43002400a

**Comment by stdedos** [comment]
> > `PIL.UnidentifiedImageError: cannot identify image file 'C:\\Users\\u\\Documents\\xpra-clients\\Xpra-Python3-x86_64_4.3-r29154\\share\\xpra\\icons\\xpra.png'`
> 
> That's definitely caused by #3133

Any plans on fixing? 😕

Upgrade is painful otherwise.

**Comment by totaam** [comment]
> Any plans on fixing? confused

I have so many plans and so little time. I've been working flat out for weeks on critical issues.
I am afraid that beta builds are not as critical as stable branches.

**Comment by stdedos** [comment]
> I have so many plans and so little time.

👍 hang in there 😀

**Comment by totaam** [comment]
f7dc3a0d9835a3bbb2c31fa09687b86890b1eba7 should have fixed this.

Please close if that works for you.

**Comment by stdedos** [comment]
There's still this
```
2021-06-21 13:30:37,626 Warning: cannot query ICC profiles:
2021-06-21 13:30:37,626  cannot import name 'ImageWin' from 'PIL' (Xpra-Python3-x86_64_4.3-r29325\lib\PIL\__init__.pyc)
```

but does not seem absolutely critical.

**Comment by totaam** [comment]
> `Warning: cannot query ICC profiles:`

Fixed. You wouldn't notice unless you used an application that use the monitor's colour profile.

**Comment by stdedos** [comment]
> Fixed. You wouldn't notice unless you used an application that use the monitor's colour profile.

Wonder which one it is 😂

Thanks 👍
