### ISSUE TITLE
Video scaling argument parsing

### ISSUE THREAD

**Issue by mattsuth** [Xpra-org/xpra#3397]
**Describe the bug**
XPRA crashes when video-scaling option is used.

**To Reproduce**
Connecting to a server via xpra from the command line, pass in "--video-scaling=0" as an argument.  This causes optparse to fail to parse with the following error:

    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 132, in main
        options, args = do_parse_cmdline(cmdline, defaults)
      File "/usr/lib/python3/dist-packages/xpra/scripts/parsing.py", line 1748, in do_parse_cmdline
        options, args = parser.parse_args(cmdline[1:])
      File "/usr/lib/python3.8/optparse.py", line 1387, in parse_args
        stop = self._process_args(largs, rargs, values)
      File "/usr/lib/python3.8/optparse.py", line 1427, in _process_args
        self._process_long_opt(rargs, values)
      File "/usr/lib/python3.8/optparse.py", line 1501, in _process_long_opt
        option.process(opt, value, values, self)
      File "/usr/lib/python3.8/optparse.py", line 784, in process
        return self.take_action(
      File "/usr/lib/python3.8/optparse.py", line 797, in take_action
        values.ensure_value(dest, []).append(value)
    AttributeError: 'str' object has no attribute 'append'

**System Information (please complete the following information):**
 - Server OS: Ubuntu 20.04
 - Client OS: Ubuntu 20.04
 - Xpra Server Version 4.2.3
 - Xpra Client Version 4.3-r0-1 (ubuntu package from xpra.org repo)

**Additional context**
If I remove the "--video-scaling=0" option from the command it connects fine.  I also attempted "--video-scaling=off" and "--video-scaling=auto" and got the same stack trace, so the problem appears to be with the parsing of the argument.

**Comment by totaam** [comment]
Ah, thanks. This broke a month ago in 1e8423593a9974afa5089782dc3dadc83c468f2d.
d3331bb9016e0ced6cef55997bb0c92c0d7ad027 fixes that. You can apply it by hand as it's tiny.

**Comment by mattsuth** [comment]
Worked like a charm, thanks!
