### ISSUE TITLE
Debian Trixie and Sid fail to build the CUDA kernels with clang

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#4424]
We have to [install clang++](https://github.com/Xpra-org/xpra/commit/97f1b03aefd3c39c2714ce8d24b91ad47ff79b1f) to build the CUDA kernels because of #4281

But now we hit a different issue:
```
Error: failed to compile CUDA kernel BGRA_to_RGBAP
 using command: ['/opt/cuda-12.6.2/bin/nvcc', '-fatbin', '-std=c++11', '--allow-unsupported-compiler', '-ccbin=clang++', '-arch=all', '-Wno-deprecated-gpu-targets', '-Xnvlink', '-ignore-host-info', '-c', 'fs/share/xpra/cuda/BGRX_to_YUV444.cu', '-o', 'fs/share/xpra/cuda/BGRX_to_YUV444.fatbin']

/usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/type_traits(1610): error: "__is_nothrow_new_constructible" is not a function or static data member
                        constexpr bool __is_nothrow_new_constructible
                                       ^
/usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/type_traits(3066): error: type name is not allowed
          bool _Dangle = __reference_converts_from_temporary(_Tp, _Res_t)
                                                                  ^
```

I am not going to delay the 5.x release for this.

**Comment by totaam** [comment]
Still no new CUDA release: https://developer.nvidia.com/cuda-toolkit-archive
Perhaps this is a good excuse for switching to the [`nvidia-cuda-toolkit`](https://packages.debian.org/trixie/nvidia-cuda-toolkit) package instead?
Or even [`pypi`: `nvidia-cuda-runtime-cu12`](https://pypi.org/project/nvidia-cuda-runtime-cu12/)?

**Comment by totaam** [comment]
I believe that switching to `-std=c++14` is enough to build on all recent tier-1 distros: 6b4f63b27990b0acbedc901150100b6a053f45e3, provided that you have a recent enough CUDA SDK - works with v12.8
